name: build
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.10']

    name: Python ${{ matrix.python-version }} build

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade codecov
        python -m pip install -r requirements.txt

    - name: Build
      run: python setup.py build

    - name: Test
      run: |
        coverage run --branch --source=stapy setup.py test
        coverage xml

    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        python-version: ${{ matrix.python-version }}
